---
deployment:
  tasks:
    - /bin/mkdir -p /DATA/u3868672/global-trans-api/tmp
    - /bin/cp app.js /DATA/u3868672/global-trans-api/app.js
    - /bin/cp config.js /DATA/u3868672/global-trans-api/config.js
    - /bin/cp package.json /DATA/u3868672/global-trans-api/package.json
    - /bin/cp package-lock.json /DATA/u3868672/global-trans-api/package-lock.json
    - /bin/rm -rf /DATA/u3868672/global-trans-api/src
    - /bin/cp -R src /DATA/u3868672/global-trans-api/src
    - /bin/rm -rf /DATA/u3868672/global-trans-api/public
    - /bin/cp -R public /DATA/u3868672/global-trans-api/public
    - /bin/touch /DATA/u3868672/global-trans-api/tmp/restart.txt